Repository ful1e5/onedark.nvim, pull requests merged in 2021-11, with the labels that each got.

#67 feat: `onedark-nvim` lualine theme improved
  CHANGELOG.md
  README.md
  lua/lualine/themes/onedark-nvim.lua
  lua/onedark/colors.lua
  lua/onedark/config.lua
  lua/onedark/extra/alacritty.lua
  lua/onedark/extra/kitty.lua
  lua/onedark/init.lua
  lua/onedark/theme.lua
  lua/onedark/util.lua
Labels: documentation, enhancement, assigned, refactor

#72 fix: #71 in normal mode
  CHANGELOG.md
  lua/onedark/theme.lua
Labels: assigned

#73 fix: missing DiffText highlighting
  lua/onedark/colors.lua
  lua/onedark/theme.lua
Labels: enhancement, assigned

#74 Remove dark background from backticks in markdown
  lua/onedark/theme.lua
Labels: assigned

#75 enhance: vscode like `nvim-cmp` highlights
  CHANGELOG.md
  lua/onedark/colors.lua
  lua/onedark/theme.lua
  lua/onedark/util.lua
Labels: documentation, enhancement, assigned
