Repository ful1e5/onedark.nvim, pull requests merged in 2021-12, with the labels that each got.

#76 enhance: `nvim-cmp` all lspkind supported
  CHANGELOG.md
  README.md
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned

#78 Link common `diff` highlights group
  CHANGELOG.md
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned

#79 Allow LineNr and CursorLineNr to be transparent
  lua/onedark/theme.lua
Labels: enhancement, assigned

#80 Add highlight to telescope.nvim's prompt counter
  lua/onedark/theme.lua
Labels: enhancement

#82 release: v0.0.3
  CHANGELOG.md
Labels: assigned

#83 feat: plugin support hop.nvim
  CHANGELOG.md
  README.md
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned

#84 refactor: lualine theme
  CHANGELOG.md
  README.md
  lua/onedark/colors.lua
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned, refactor

#85 feat: basic coc.nvim diagnostic highlights supported
  CHANGELOG.md
  README.md
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned

#86 Some minor Changes
  CHANGELOG.md
  lua/onedark/colors.lua
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned, refactor

#87 Statusline config added in README.md
  README.md
Labels: documentation, enhancement, assigned

#89 dev: define global in project `luarc` config file.
  .luarc.json
  CHANGELOG.md
Labels: documentation, enhancement, assigned

#90 feat: config option added `hide_end_of_buffer`
  CHANGELOG.md
  README.md
  lua/onedark/colors.lua
  lua/onedark/config.lua
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned

#92 Refactor override function to util.lua module
  CHANGELOG.md
  README.md
  lua/onedark/config.lua
  lua/onedark/theme.lua
  lua/onedark/util.lua
Labels: documentation, assigned, refactor

#93 docs: inspiration links updated
  README.md
Labels: documentation, assigned
