Repository ful1e5/onedark.nvim, pull requests merged in 2021-10, with the labels that each got.

#47 breaking change: consistent variable naming in `onedark` config
  CHANGELOG.md
  README.md
  lua/lualine/themes/onedark.lua
  lua/onedark/colors.lua
  lua/onedark/config.lua
  lua/onedark/extra/alacritty.lua
  lua/onedark/extra/init.lua
  lua/onedark/extra/kitty.lua
  lua/onedark/init.lua
  lua/onedark/theme.lua
Labels: documentation, assigned, refactor, hacktoberfest

#48 Add code of conduct
  CODE_OF_CONDUCT.md
  extras/alacritty_onedark.yml
  lua/onedark/extra/alacritty.lua
Labels: documentation, assigned

#49 docs: prepare for #hacktoberfest
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation, assigned

#50 Fixed typo `darkSidebar` on configuration table.
  README.md
Labels: documentation, assigned, hacktoberfest

#51 fix: reload with 'colorscheme' command
  colors/onedark.lua
Labels: assigned

#52 feat: highlight_linenumber config for setting dark color to number-line
  CHANGELOG.md
  README.md
  lua/onedark/colors.lua
  lua/onedark/config.lua
  lua/onedark/theme.lua
Labels: documentation, enhancement, assigned, hacktoberfest

#65 feat(themes): add lualine theme
  lua/lualine/themes/onedark-nvim.lua
Labels: enhancement, assigned
